name: Pull Request Run
run-name: ${{ github.actor }} thanks you for you Submission! 
on: [pull_request]
jobs:
  On-PullRequest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  install:
    runs-on: ubuntu-latest
  
    steps:
    - run: yarn install

  test:
    runs-on: ubuntu-latest
  
    needs: install

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - run: yarn run test