name: Pull Request Run
run-name: ${{ github.actor }} thanks you for you Submission! 
on: [pull_request]
jobs:
  On-PullRequest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  install:
    runs-on: ubuntu-latest
  
    steps:
    - run: yarn install